namespace ShopeeManagement.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class sdf : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.TitleModels", new[] { "TitleBrand_Id", "TitleBrand_UserId" }, "dbo.TitleBrands");
            DropForeignKey("dbo.TitleBrands", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes");
            DropForeignKey("dbo.TitleFeatures", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes");
            DropForeignKey("dbo.TitleGroups", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes");
            DropForeignKey("dbo.TitleModels", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes");
            DropForeignKey("dbo.TitleOptions", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes");
            DropForeignKey("dbo.TitleRelats", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes");
            DropForeignKey("dbo.TemplateFooters", new[] { "SetFooter_Id", "SetFooter_UserId" }, "dbo.SetFooters");
            DropForeignKey("dbo.TemplateHeaders", new[] { "SetHeader_Id", "SetHeader_UserId" }, "dbo.SetHeaders");
            DropIndex("dbo.TemplateFooters", new[] { "SetFooter_Id", "SetFooter_UserId" });
            DropIndex("dbo.TemplateHeaders", new[] { "SetHeader_Id", "SetHeader_UserId" });
            DropIndex("dbo.TitleBrands", new[] { "TitleType_Id", "TitleType_UserId" });
            DropIndex("dbo.TitleModels", new[] { "TitleBrand_Id", "TitleBrand_UserId" });
            DropIndex("dbo.TitleModels", new[] { "TitleType_Id", "TitleType_UserId" });
            DropIndex("dbo.TitleFeatures", new[] { "TitleType_Id", "TitleType_UserId" });
            DropIndex("dbo.TitleGroups", new[] { "TitleType_Id", "TitleType_UserId" });
            DropIndex("dbo.TitleOptions", new[] { "TitleType_Id", "TitleType_UserId" });
            DropIndex("dbo.TitleRelats", new[] { "TitleType_Id", "TitleType_UserId" });
            //DropColumn("dbo.TemplateFooters", "SetFooterId");
            //DropColumn("dbo.TemplateFooters", "UserId");
            //DropColumn("dbo.TemplateHeaders", "SetHeaderId");
            //DropColumn("dbo.TemplateHeaders", "UserId");
            //RenameColumn(table: "dbo.TemplateFooters", name: "SetFooter_Id", newName: "SetFooterId");
            //RenameColumn(table: "dbo.TemplateFooters", name: "SetFooter_UserId", newName: "UserId");
            //RenameColumn(table: "dbo.TemplateHeaders", name: "SetHeader_Id", newName: "SetHeaderId");
            //RenameColumn(table: "dbo.TemplateHeaders", name: "SetHeader_UserId", newName: "UserId");
            DropPrimaryKey("dbo.ConfigVars");
            DropPrimaryKey("dbo.CurrencyRates");
            DropPrimaryKey("dbo.CustomCategoryDatas");
            DropPrimaryKey("dbo.DesignStyles");
            DropPrimaryKey("dbo.FavKeywordOthers");
            DropPrimaryKey("dbo.FavKeywords");
            DropPrimaryKey("dbo.FavoriteCategoryDatas");
            DropPrimaryKey("dbo.FooterSeparators");
            DropPrimaryKey("dbo.Logistics");
            DropPrimaryKey("dbo.ProductAttributes");
            DropPrimaryKey("dbo.ProductLinks");
            DropPrimaryKey("dbo.Promotions");
            DropPrimaryKey("dbo.SetFooters");
            DropPrimaryKey("dbo.TemplateFooters");
            DropPrimaryKey("dbo.SetHeaders");
            DropPrimaryKey("dbo.TemplateHeaders");
            DropPrimaryKey("dbo.ShopeeAccounts");
            DropPrimaryKey("dbo.ShopeeCategoryOnlies");
            DropPrimaryKey("dbo.ShopeeVariationPrices");
            DropPrimaryKey("dbo.TitleBrands");
            DropPrimaryKey("dbo.TitleModels");
            DropPrimaryKey("dbo.TitleTypes");
            DropPrimaryKey("dbo.TitleFeatures");
            DropPrimaryKey("dbo.TitleGroups");
            DropPrimaryKey("dbo.TitleOptions");
            DropPrimaryKey("dbo.TitleRelats");
            AlterColumn("dbo.ConfigVars", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.CurrencyRates", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.CustomCategoryDatas", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.DesignStyles", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.FavKeywordOthers", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.FavKeywords", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.FavoriteCategoryDatas", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.FooterSeparators", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.Logistics", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.ProductAttributes", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.ProductLinks", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.Promotions", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.SetFooters", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.SetFooters", "SetFooterName", c => c.String(maxLength: 150));
            AlterColumn("dbo.TemplateFooters", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TemplateFooters", "ShopeeAccount", c => c.String(maxLength: 150));
            AlterColumn("dbo.TemplateFooters", "HFName", c => c.String(maxLength: 150));
            AlterColumn("dbo.TemplateFooters", "SetFooterId", c => c.Int(nullable: false));
            AlterColumn("dbo.TemplateFooters", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.SetHeaders", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TemplateHeaders", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TemplateHeaders", "SetHeaderId", c => c.Int(nullable: false));
            AlterColumn("dbo.TemplateHeaders", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.ShopeeAccounts", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.ShopeeCategoryOnlies", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.ShopeeVariationPrices", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleBrands", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleModels", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleTypes", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleFeatures", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleGroups", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleOptions", "UserId", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.TitleRelats", "UserId", c => c.String(nullable: false, maxLength: 150));
            AddPrimaryKey("dbo.ConfigVars", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.CurrencyRates", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.CustomCategoryDatas", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.DesignStyles", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.FavKeywordOthers", new[] { "Keyword", "UserId" });
            AddPrimaryKey("dbo.FavKeywords", new[] { "Keyword", "UserId" });
            AddPrimaryKey("dbo.FavoriteCategoryDatas", new[] { "shopeeId", "category3_id", "UserId" });
            AddPrimaryKey("dbo.FooterSeparators", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.Logistics", new[] { "shopeeAccount", "logistic_id", "UserId" });
            AddPrimaryKey("dbo.ProductAttributes", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.ProductLinks", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.Promotions", new[] { "shopeeAccount", "discount_id", "UserId" });
            AddPrimaryKey("dbo.SetFooters", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TemplateFooters", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.SetHeaders", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TemplateHeaders", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.ShopeeAccounts", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.ShopeeCategoryOnlies", new[] { "ID", "UserId" });
            AddPrimaryKey("dbo.ShopeeVariationPrices", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.TitleBrands", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleModels", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleTypes", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleFeatures", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleGroups", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleOptions", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleRelats", new[] { "Id", "UserId" });
            CreateIndex("dbo.TemplateFooters", new[] { "SetFooterId", "UserId" });
            CreateIndex("dbo.TemplateHeaders", new[] { "SetHeaderId", "UserId" });
            AddForeignKey("dbo.TemplateFooters", new[] { "SetFooterId", "UserId" }, "dbo.SetFooters", new[] { "Id", "UserId" }, cascadeDelete: true);
            AddForeignKey("dbo.TemplateHeaders", new[] { "SetHeaderId", "UserId" }, "dbo.SetHeaders", new[] { "Id", "UserId" }, cascadeDelete: true);
            //DropColumn("dbo.TitleBrands", "TitleType_Id");
            //DropColumn("dbo.TitleBrands", "TitleType_UserId");
            //DropColumn("dbo.TitleModels", "TitleBrand_Id");
            //DropColumn("dbo.TitleModels", "TitleBrand_UserId");
            //DropColumn("dbo.TitleModels", "TitleType_Id");
            //DropColumn("dbo.TitleModels", "TitleType_UserId");
            //DropColumn("dbo.TitleFeatures", "TitleType_Id");
            //DropColumn("dbo.TitleFeatures", "TitleType_UserId");
            //DropColumn("dbo.TitleGroups", "TitleType_Id");
            //DropColumn("dbo.TitleGroups", "TitleType_UserId");
            //DropColumn("dbo.TitleOptions", "TitleType_Id");
            //DropColumn("dbo.TitleOptions", "TitleType_UserId");
            //DropColumn("dbo.TitleRelats", "TitleType_Id");
            //DropColumn("dbo.TitleRelats", "TitleType_UserId");
        }
        
        public override void Down()
        {
            //AddColumn("dbo.TitleRelats", "TitleType_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleRelats", "TitleType_Id", c => c.Int());
            //AddColumn("dbo.TitleOptions", "TitleType_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleOptions", "TitleType_Id", c => c.Int());
            //AddColumn("dbo.TitleGroups", "TitleType_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleGroups", "TitleType_Id", c => c.Int());
            //AddColumn("dbo.TitleFeatures", "TitleType_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleFeatures", "TitleType_Id", c => c.Int());
            //AddColumn("dbo.TitleModels", "TitleType_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleModels", "TitleType_Id", c => c.Int());
            //AddColumn("dbo.TitleModels", "TitleBrand_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleModels", "TitleBrand_Id", c => c.Int());
            //AddColumn("dbo.TitleBrands", "TitleType_UserId", c => c.String(maxLength: 128));
            //AddColumn("dbo.TitleBrands", "TitleType_Id", c => c.Int());
            DropForeignKey("dbo.TemplateHeaders", new[] { "SetHeaderId", "UserId" }, "dbo.SetHeaders");
            DropForeignKey("dbo.TemplateFooters", new[] { "SetFooterId", "UserId" }, "dbo.SetFooters");
            DropIndex("dbo.TemplateHeaders", new[] { "SetHeaderId", "UserId" });
            DropIndex("dbo.TemplateFooters", new[] { "SetFooterId", "UserId" });
            DropPrimaryKey("dbo.TitleRelats");
            DropPrimaryKey("dbo.TitleOptions");
            DropPrimaryKey("dbo.TitleGroups");
            DropPrimaryKey("dbo.TitleFeatures");
            DropPrimaryKey("dbo.TitleTypes");
            DropPrimaryKey("dbo.TitleModels");
            DropPrimaryKey("dbo.TitleBrands");
            DropPrimaryKey("dbo.ShopeeVariationPrices");
            DropPrimaryKey("dbo.ShopeeCategoryOnlies");
            DropPrimaryKey("dbo.ShopeeAccounts");
            DropPrimaryKey("dbo.TemplateHeaders");
            DropPrimaryKey("dbo.SetHeaders");
            DropPrimaryKey("dbo.TemplateFooters");
            DropPrimaryKey("dbo.SetFooters");
            DropPrimaryKey("dbo.Promotions");
            DropPrimaryKey("dbo.ProductLinks");
            DropPrimaryKey("dbo.ProductAttributes");
            DropPrimaryKey("dbo.Logistics");
            DropPrimaryKey("dbo.FooterSeparators");
            DropPrimaryKey("dbo.FavoriteCategoryDatas");
            DropPrimaryKey("dbo.FavKeywords");
            DropPrimaryKey("dbo.FavKeywordOthers");
            DropPrimaryKey("dbo.DesignStyles");
            DropPrimaryKey("dbo.CustomCategoryDatas");
            DropPrimaryKey("dbo.CurrencyRates");
            DropPrimaryKey("dbo.ConfigVars");
            AlterColumn("dbo.TitleRelats", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TitleOptions", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TitleGroups", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TitleFeatures", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TitleTypes", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TitleModels", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TitleBrands", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ShopeeVariationPrices", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ShopeeCategoryOnlies", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ShopeeAccounts", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TemplateHeaders", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.TemplateHeaders", "SetHeaderId", c => c.Int());
            AlterColumn("dbo.TemplateHeaders", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SetHeaders", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TemplateFooters", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.TemplateFooters", "SetFooterId", c => c.Int());
            AlterColumn("dbo.TemplateFooters", "HFName", c => c.String());
            AlterColumn("dbo.TemplateFooters", "ShopeeAccount", c => c.String());
            AlterColumn("dbo.TemplateFooters", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SetFooters", "SetFooterName", c => c.String());
            AlterColumn("dbo.SetFooters", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Promotions", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ProductLinks", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ProductAttributes", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Logistics", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.FooterSeparators", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.FavoriteCategoryDatas", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.FavKeywords", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.FavKeywordOthers", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.DesignStyles", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.CustomCategoryDatas", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.CurrencyRates", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ConfigVars", "UserId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.TitleRelats", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleOptions", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleGroups", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleFeatures", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleTypes", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleModels", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TitleBrands", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.ShopeeVariationPrices", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.ShopeeCategoryOnlies", new[] { "ID", "UserId" });
            AddPrimaryKey("dbo.ShopeeAccounts", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.TemplateHeaders", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.SetHeaders", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.TemplateFooters", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.SetFooters", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.Promotions", new[] { "shopeeAccount", "discount_id", "UserId" });
            AddPrimaryKey("dbo.ProductLinks", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.ProductAttributes", new[] { "Id", "UserId" });
            AddPrimaryKey("dbo.Logistics", new[] { "shopeeAccount", "logistic_id", "UserId" });
            AddPrimaryKey("dbo.FooterSeparators", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.FavoriteCategoryDatas", new[] { "shopeeId", "category3_id", "UserId" });
            AddPrimaryKey("dbo.FavKeywords", new[] { "Keyword", "UserId" });
            AddPrimaryKey("dbo.FavKeywordOthers", new[] { "Keyword", "UserId" });
            AddPrimaryKey("dbo.DesignStyles", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.CustomCategoryDatas", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.CurrencyRates", new[] { "Idx", "UserId" });
            AddPrimaryKey("dbo.ConfigVars", new[] { "Id", "UserId" });
            RenameColumn(table: "dbo.TemplateHeaders", name: "UserId", newName: "SetHeader_UserId");
            RenameColumn(table: "dbo.TemplateHeaders", name: "SetHeaderId", newName: "SetHeader_Id");
            RenameColumn(table: "dbo.TemplateFooters", name: "UserId", newName: "SetFooter_UserId");
            RenameColumn(table: "dbo.TemplateFooters", name: "SetFooterId", newName: "SetFooter_Id");
            AddColumn("dbo.TemplateHeaders", "UserId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.TemplateHeaders", "SetHeaderId", c => c.Int(nullable: false));
            AddColumn("dbo.TemplateFooters", "UserId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.TemplateFooters", "SetFooterId", c => c.Int(nullable: false));
            CreateIndex("dbo.TitleRelats", new[] { "TitleType_Id", "TitleType_UserId" });
            CreateIndex("dbo.TitleOptions", new[] { "TitleType_Id", "TitleType_UserId" });
            CreateIndex("dbo.TitleGroups", new[] { "TitleType_Id", "TitleType_UserId" });
            CreateIndex("dbo.TitleFeatures", new[] { "TitleType_Id", "TitleType_UserId" });
            CreateIndex("dbo.TitleModels", new[] { "TitleType_Id", "TitleType_UserId" });
            CreateIndex("dbo.TitleModels", new[] { "TitleBrand_Id", "TitleBrand_UserId" });
            CreateIndex("dbo.TitleBrands", new[] { "TitleType_Id", "TitleType_UserId" });
            CreateIndex("dbo.TemplateHeaders", new[] { "SetHeader_Id", "SetHeader_UserId" });
            CreateIndex("dbo.TemplateFooters", new[] { "SetFooter_Id", "SetFooter_UserId" });
            AddForeignKey("dbo.TemplateHeaders", new[] { "SetHeader_Id", "SetHeader_UserId" }, "dbo.SetHeaders", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TemplateFooters", new[] { "SetFooter_Id", "SetFooter_UserId" }, "dbo.SetFooters", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleRelats", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleOptions", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleModels", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleGroups", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleFeatures", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleBrands", new[] { "TitleType_Id", "TitleType_UserId" }, "dbo.TitleTypes", new[] { "Id", "UserId" });
            AddForeignKey("dbo.TitleModels", new[] { "TitleBrand_Id", "TitleBrand_UserId" }, "dbo.TitleBrands", new[] { "Id", "UserId" });
        }
    }
}
